-- MySQL Script generated by MySQL Workbench
-- Jum 18 Okt 2019 12:14:03  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `user` ;

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8 ;
USE `user` ;

-- -----------------------------------------------------
-- Table `user`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user` ;

CREATE TABLE IF NOT EXISTS `user`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`chat` ;

CREATE TABLE IF NOT EXISTS `user`.`chat` (
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`.`chat_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`chat_message` ;

CREATE TABLE IF NOT EXISTS `user`.`chat_message` (
  `id` INT NOT NULL,
  `chat_id` BIGINT NOT NULL,
  `user_id` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_message_chat_idx` (`chat_id` ASC),
  INDEX `fk_chat_message_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_chat_message_chat`
    FOREIGN KEY (`chat_id`)
    REFERENCES `user`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `user`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`user` (`id`, `username`, `password`) VALUES (1, 'wowotek', 'ff84abb1970b527abf2e96539a5944c844ef5c42df3c6479cda7d64543cdf3e1326878f388587c3aa8913b6aed65f408fa177236357607c22df75d1e1ef38d22');
INSERT INTO `user`.`user` (`id`, `username`, `password`) VALUES (2, 'gajahmu', '385b5fb3512f87533f59837c26d0337dd8f3c7056e9607eb66e78fbc00fcdd52c6a5a3302eaf834df860379d8654924b00e5b34a059709c998bdc54772b794b2');

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`.`chat`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`chat` (`id`) VALUES (1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`.`chat_message`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`chat_message` (`id`, `chat_id`, `user_id`, `content`, `created_at`) VALUES (1, 1, 1, 'hello gajah! nice to meet ya', DEFAULT);
INSERT INTO `user`.`chat_message` (`id`, `chat_id`, `user_id`, `content`, `created_at`) VALUES (2, 1, 1, 'how are you?', DEFAULT);
INSERT INTO `user`.`chat_message` (`id`, `chat_id`, `user_id`, `content`, `created_at`) VALUES (3, 1, 2, 'hey ! nice to meet you too wowotek', DEFAULT);

COMMIT;

